project:
  type: website
  output-dir: docs
  preview:
    port: 7303

filters:
  - shinylive

website:
  title: "zeemarquez.github.io"
  site-url: "https:/zeemarquez.github.io"
  google-analytics: "G-MLEV5LTVX2"
  open-graph: true
  navbar:
    logo: home.png
    title: false

    right:
      - icon: person-circle
        file: about.qmd
        text: " "

      - icon: github
        href: https://github.com/zeemarquez

      - text: "en / es"
        menu:
        - text: "English"
          file: index.qmd
        - text: "Español"
          file: index_es.qmd
       
format:
  html:
    theme: litera
    css: styles.css
    code-tools: true
    highlight-style: github
    syntax-definitions: 
    - python.xml
    
    




