project:
  type: website
  output-dir: docs

filters:
  - shinylive

website:
  title: "zeemarquez.github.io"
  open-graph: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: litera
    css: styles.css
    code-tools: true
    highlight-style: github
    




